### ISSUE TITLE
Add @NonNullApi and @Nullable annotations

### ISSUE THREAD

**Issue by acogoluegnes** [reactor/reactor-rabbitmq#111]
Per discussion with @simonbasle.

**Comment by vanseverk** [comment]
Is this something I can take onto me? What's the goal?

**Comment by acogoluegnes** [comment]
@vanseverk Sure, go ahead. The idea is to add `@reactor.util.annotation.NonNullApi` to the `reactor.rabbitmq` package, which means that all parameters and return values are non-null and then use `@reactor.util.annotation.Nullable` in places they can be null.

Maybe @simonbasle has more recommendations.

**Comment by simonbasle** [comment]
@acogoluegnes @vanseverk that's pretty much it: non-null by default (eased by putting the annotation on the `package-info.java`) and mark nullable methods (return types and input parameters)

**Comment by acogoluegnes** [comment]
Closed in #113.
