### ISSUE TITLE
RabbitMQ cluster support

### ISSUE THREAD

**Issue by eksd** [reactor/reactor-rabbitmq#12]
Is it possible now to connect to the rabbitmq cluster with many nodes?
Unfortunately, Receiver has not any methods for this, although ConnectionFactory has.

**Comment by acogoluegnes** [comment]
`ReceiverOptions` has [a `ConnectionFactory` property](https://github.com/reactor/reactor-rabbitmq/blob/af832a0da9a79c9134fdc4f43cf1eef5719b0185/src/main/java/reactor/rabbitmq/ReceiverOptions.java#L26), this is where you can specify the host(s) you want to connect to.

**Comment by eksd** [comment]
ConnectionFactory has just methods that [create Connection from many addresses](https://github.com/rabbitmq/rabbitmq-java-client/blob/10be9512e3091327b0f7cafdc3076b2d60b9780f/src/main/java/com/rabbitmq/client/ConnectionFactory.java#L728) but not ConnectionFactory.

It seems to me that SenderOptions and ReceiverOptions should have Addresses field and setter for it.
And when we call createSender/createReceiver method,  we should check if this field is null or not and depending on the result to call simple [newConnection](https://github.com/reactor/reactor-rabbitmq/blob/af832a0da9a79c9134fdc4f43cf1eef5719b0185/src/main/java/reactor/rabbitmq/Sender.java#L79) or [newConnection(addrs)](https://github.com/rabbitmq/rabbitmq-java-client/blob/10be9512e3091327b0f7cafdc3076b2d60b9780f/src/main/java/com/rabbitmq/client/ConnectionFactory.java#L728).

If you think it's a good idea, I'm ready to create PR.

**Comment by acogoluegnes** [comment]
@eksd Fair enough, the connection creation is currently too encapsulated to connect to several different servers. Feel free to submit a PR with a workaround. Thanks!

**Comment by acogoluegnes** [comment]
@eksd There's now an option to create a connection from the connection factory, both in [`Sender`](http://projectreactor.io/docs/rabbitmq/snapshot/reference/#api-guide-sender) and in [`Receiver`](http://projectreactor.io/docs/rabbitmq/snapshot/reference/#api-guide-receiver).
