### ISSUE TITLE
Provide an an easy way to supply clientProvidedConnection name

### ISSUE THREAD

**Issue by a701440** [reactor/reactor-rabbitmq#120]
Rabbit connection factory has an API ConnectionFactory.newConnection that takes a connection name. It appears that by default invokes the newConnection with no parameters:

Mono.fromCallable(() -> options.getConnectionFactory().newConnection())

Would it be possible to add a strategy class to generate the client provided connection name to the SenderOptions and ReceiverOptions?

**Comment by acogoluegnes** [comment]
Both `ReceiverOptions` and `SenderOptions` have a `connectionSupplier` method to provide a function to create the connection from the connection factory. This can be used like the following:

```java
options.connectionSupplier(cf, connectionFactory -> cf.newConnection("my-connection-name"));
```
