### ISSUE TITLE
Missing Exchange to Exchange binding API

### ISSUE THREAD

**Issue by cambierr** [reactor/reactor-rabbitmq#121]
The library is great but lacks a major feature which is Exchange to Exchange bindings

## Motivation
For the project I'm currently working on, I need to setup multiple exchanges binding with an exchange-to-exchange topology.

My use cases is that events are published no a lot of different exchanges (one by event type) and we have a single sharded exchange to should receive a copy of messages going through all the other to permit a sharded processing (see x-consistent-hash plugin)

## Desired solution
Duplicate the `BindingSpecification` to `ExchangeBindingSpecification` and `QueueBindingSpecification`, deprecate the existing one and duplicate the `Sender.bind(...)` to get two implementations depending of the incoming specification type

## Considered alternatives
The only way (for now) is to use the direct rabbitmq channels which removes a significant part of the benefits generated by this library

## Additional context
N/A

**Comment by acogoluegnes** [comment]
This is certainly doable.

I was thinking we could expand `BindingSpecification` with a new property (could be `exchangeTo`, and there could be also `exchangeFrom`, the latter being just an alias of `exchange`). WDYT?

**Comment by cambierr** [comment]
LGTM. I actually can even write a PR tomorrow

**Comment by acogoluegnes** [comment]
> LGTM. I actually can even write a PR tomorrow

Great, thanks, you're welcome to contribute a PR.

**Comment by acogoluegnes** [comment]
@cambierr Are still planning to write a PR for this one or should I handle it?

**Comment by cambierr** [comment]
Sadly, I won't be able to do it before one or two weeks because of unexpected work loads...
So it's probably better if you can do it so that other people looking at this can benefit from it ASAP.

**Comment by acogoluegnes** [comment]
@cambierr I created a PR with the exchange-to-exchange binding feature if you want to take a look before I merge it.

**Comment by cambierr** [comment]
Great !! thank you :-)
