### ISSUE TITLE
Any interest in improving consume method's Flux backpressure?

### ISSUE THREAD

**Issue by jspengeman** [reactor/reactor-rabbitmq#126]
It would be ideal if the Flux's created in the consume methods applied back pressure to RabbitMQ. As it is right now [this code](https://github.com/reactor/reactor-rabbitmq/blob/master/src/main/java/reactor/rabbitmq/Receiver.java#L190) appears to send messages downstream at an unbounded rate since the consumer just listens for all messages. If you have a very busy queue and slow consumers, I could easily see you running into overflow issues. 

Ideally, downstream could send some "demand" for messages upstream to the Flux being created in the consume methods and then the Flux would handle that demand by pulling that many messages of of the queue. This way the consumer can't send messages at unbounded rate. Downstream is in control of the rate of messages by asking for more. 

I know RabbitMQ supports a [pull API](https://www.rabbitmq.com/api-guide.html#getting) but it only supports getting a single message at a time. To do this without any internal buffering in the flux I think you'd need a batch get style API endpoint, which doesn't exist unfortunately.

I'd be happy to investigate this further. I just wanted to start a discussion first and see if there was any interest in functionality like this (I am certainly interested in it :wink:)

Looking forward to hearing others' thoughts.

**Comment by acogoluegnes** [comment]
It is already possible to throttle incoming messages by using `ConsumeOptions#qos` and acknowledgement. So the rate is unbounded only when using auto-acknowledgment.

I'm all for improving the library to avoid overflowing downstream. It would be interesting to see if downstream requests could be propagated up to the server. I'm not aware of anyone having experimented with that.
