### ISSUE TITLE
Opened channels leaked and mapper return NullPointerException while create new channel for executing rpc request

### ISSUE THREAD

**Issue by kubitre** [reactor/reactor-rabbitmq#129]
I using your library for rpc request response pattern in rabbitmq. I opened 1 connection to rabbitmq and next i use RpcClient for sending request. At the end, after more requests by this library for 1 opened connection i had channels leaked. When i checked by debug i find that channels only create but not closing. Maybe i do wrong or maybe u can get me advice for this case?

#### Language: kotlin 1.3.7

Code: 
opening connection by ConnectionFactory of AMQP library:
```kotlin

    fun initNewConnection() = runBlocking {
        connection?.run {
            withContext(Dispatchers.IO) {
                awaitFirstOrNull()?.run {
                    logger.debug("current available channels: ${this.channelMax}")
                    if (!isOpen) {
                        this.close()
                    }
                }
            }
        } ?: run {
            connection = Mono.fromCallable(Callable { factory.newConnection("consumer-rabbit") }).cache()
        }
    }
```

And after i had connection to rabbitmq i using this connection for producing messages in rabbitmq look like this:
```kotlin
      val genRespQueueName = "reply_queue_${UUID.randomUUID()}"
        val corrID = UUID.randomUUID().toString()
        val props = AMQP.BasicProperties()
            .builder()
 //// there is my additional params for rabbitmq
            .build()
        val rpcCli = rpcSender
            .rpcClient(exchangeName, queueName)

        return rpcCli.rpc(Mono.just(RpcClient.RpcRequest(props, message))).awaitFirstOrNull()
```

And rpcSender look like this:
```kotlin
 fun producerRPC(senderOptions: ProducerSenderOptions.SenderOptions): Sender {
        return RabbitFlux.createSender(senderOptions.senderOptions)
    }
```

**Comment by kubitre** [comment]
@acogoluegnes may be u can help me?

**Comment by acogoluegnes** [comment]
This is covered in the [documentation](https://projectreactor.io/docs/rabbitmq/release/reference/#_request_reply):

> RpcClient#close() does not close the underlying Channel the RpcClient uses. When creating the RpcClient with Sender#rpcClient the Sender instance provides a Channel that will be closed when the Sender is closed. It is possible to provide a given Mono<Channel> by using the RpcClient constructor, but the Channel will then need to be explicitly closed as well.

A `RpcClient` re-uses the channel it's been created with and don't take the initiative to close it.

You should consider re-using the `RpcClient` instances you create or creating them with a `Mono<Channel>` that caches the channel (to avoid churn, channels require a network round trip to be created). Then you should be take of closing the channels when they're no longer required.

**Comment by kubitre** [comment]
okay but if i have using 1 connection for sending to many that one different queues. In 1 rpc client i can not do this. Therefore i should have clean up all cachable channels

**Comment by acogoluegnes** [comment]
OK, so you need to send messages to different destinations (exchange/routing key).

If the destinations are known in advance, it's possible to create the `RpcClient` instances in advance and re-use them. You can close the channels (or the connection) when the application closes.

If they're not known in advance, you have to create `RpcClient` instances on the client, but they can share the same cached `Mono<Channel>`. If it's not possible, you may create a new channel every time, this can work but is not optimal.

At last, we can add `exchange` and `routingKey` optional properties to `RpcRequest` to make the `RpcClient` more flexible.

**Comment by kubitre** [comment]
maybe u can take me article with best practice on rpc by the way? Thanks for u attention and help. 
I writed self "gc" for channels

**Comment by acogoluegnes** [comment]
There's the [RPC tutorial](https://www.rabbitmq.com/tutorials/tutorial-six-java.html) and the [direct reply-to](https://www.rabbitmq.com/direct-reply-to.html) optimization.

**Comment by kubitre** [comment]
Thanks

**Comment by jamb1975** [comment]
I use ChannelPool= ChannelPoolFactory.createChannelPool(monoConnection, new ChannelPoolOption().maxCacheSize(7));
