### ISSUE TITLE
Stop relying on rabbitmq ConnectionFactory to enable shared connections etc

### ISSUE THREAD

**Issue by piotrblasiak** [reactor/reactor-rabbitmq#13]
I am already using spring-amqp and its CachingConnectionFactory so that I only have one shared connection and use multiple channels per thread instead as seems to be more efficient than having multiple connections. Is there a reason why Receiver wants to have its own Connection?

If sharing a Connection is OK, I suggest changing the ReceiverOptions class (and others, where applicable) in one of the following ways:

1) If a channel is all that is needed, give it a Channel instance or at least a ChannelFactory interface instead. Being able to give the receiver a specific channel instead of having it create a new one will enable channel sharing which is necessary in some cases where you want to add/remove bindings to a queue that is being exclusively consumed by a channel.

2) If a Connection is really needed, use a simple ConnectionFactory interface instead of relying on the rabbitmq ConnectionFactory class. We can then wrap the CachingConnectionFactory from spring-amqp and use that instead.

I hope this makes sense.

**Comment by acogoluegnes** [comment]
This makes sense to me, even I need to check the exact semantics for the different cases the receiver covers. I prefer option 1 over option 2, as the latter would introduce a dependency to Spring AMQP.

**Comment by acogoluegnes** [comment]
Maybe a `Supplier<Connection>` would be enough to work against exclusive queues.

**Comment by acogoluegnes** [comment]
Fixed in e89f912.

**Comment by acogoluegnes** [comment]
@piotrblasiak Connection is now implemented and [documented](http://projectreactor.io/docs/rabbitmq/snapshot/reference/#_sharing_the_same_connection_between_code_sender_code_and_code_receiver_code).

**Comment by piotrblasiak** [comment]
Very nice. Thanks!
