### ISSUE TITLE
Expose basicReject when using AcknowledgableDelivery.

### ISSUE THREAD

**Issue by mxandeco** [reactor/reactor-rabbitmq#137]
When using manual ack the AcknowledgableDelivery class will offer an `ack` and `nack`, delegating to `Channel#basicAck` and `Channel#ack`, there are cases when rejecting the message is desired.

The reject operation is similar from ack/nack and exposed by Channel#reject.

Am I missing a reason that method is not available when using AcknowledgableDelivery, or is just not there yet?

**Comment by acogoluegnes** [comment]
`basic.nack` has the same effect as `basic.reject`, except it can reject messages in bulk. This is a RabbitMQ extension, see the [documentation](https://www.rabbitmq.com/nack.html). So there's no use exposing `basic.reject` here, because `basic.nack` allows to do the exact same things, and more.

**Comment by mxandeco** [comment]
> `basic.nack` has the same effect as `basic.reject`, except it can reject messages in bulk. This is a RabbitMQ extension, see the [documentation](https://www.rabbitmq.com/nack.html). So there's no use exposing `basic.reject` here, because `basic.nack` allows to do the exact same things, and more.

Oh right, I assumed the `reject` had a different meaning based on some issues I am having with DLX, but it's probably have misconfiguration on my queues then bases on that link.

Thanks.
