### ISSUE TITLE
Provide a "standalone" ack/nack method.

### ISSUE THREAD

**Issue by mxandeco** [reactor/reactor-rabbitmq#139]
We are exposing a sort of http streaming for clients that can't use our java client directly, basically we start a manualAck consumer and expose the result Flux using spring-web-flux.

We need to provide a way for those clients to ack messages manually, "out of the scope" of the manualAck consumer, we do we have a different http endpoint for that feature.

Reactor-Rabbit won't offer any method for that atm, we then need to keep a instance of the classic rabbitmq client on our own, would be possible to expose the basicAck/Nack methods on the receiver/sender?

Another option would work for us, would expose the managed channel that we could use, without having to worry about handling the connection. that might cause issues for the rabbit-flux?

We are happy to put a change request for the basicAck/Nack, if it's acceptable for them to be exposed on this library.

Thanks

**Comment by acogoluegnes** [comment]
With `Receiver#consumeManualAck`, you get a `Flux<AcknowledgableDelivery>`, you can call `AcknowledgableDelivery#ack()` to ack those messages. I guess you know that already.

The ack cannot be totally out of context, you need at least the delivery tag (from the envelope) and the channel. An `AcknowledgableDelivery` instance contains its channel, it uses it in the `ack` method. What context from the message do you have in the HTTP endpoint you're mentioning?

I'd say the tricky part is to have access to the `Channel`, I see a couple of options:
  * extract it with reflection from `AcknowledgableDelivery` instances (ugly?)
  * adding a `Consumer<Channel>` callback property in `ConsumeOptions`. It would be called in `Receiver#consumeManualAck` with the channel allocated for this `Flux<AcknowledgableDelivery>`. This way you could keep a reference to the channel used for a given subscription and you would be able to ack the messages whenever you want. Would that work?

**Comment by mxandeco** [comment]
> With `Receiver#consumeManualAck`, you get a `Flux<AcknowledgableDelivery>`, you can call `AcknowledgableDelivery#ack()` to ack those messages. I guess you know that already.
> 
> The ack cannot be totally out of context, you need at least the delivery tag (from the envelope) and the channel. An `AcknowledgableDelivery` instance contains its channel, it uses it in the `ack` method. What context from the message do you have in the HTTP endpoint you're mentioning?
> 
> I'd say the tricky part is to have access to the `Channel`, I see a couple of options:
> 
> * extract it with reflection from `AcknowledgableDelivery` instances (ugly?)
> * adding a `Consumer<Channel>` callback property in `ConsumeOptions`. It would be called in `Receiver#consumeManualAck` with the channel allocated for this `Flux<AcknowledgableDelivery>`. This way you could keep a reference to the channel used for a given subscription and you would be able to ack the messages whenever you want. Would that work?

Yes, we do handle message consuming with `AcknowledgableDelivery#ack()` for java clients.

On the http server we have access to any property of the message, but its "stateless" atm, we would have only data, we do not really encourage usage of this http, but there are few cases where we do not have option.

I think keeping the reference you mentioned would work for some cases, but if that channel is closed we no longer have the way to ack the message, or if we run more than one replica we also cannot guarantee we have the channel. I think I completely  missed the need of the channel to ack messages when started the writing this http support.

Maybe the best way for us to handle this, would be to have a unique identifier in the message, and when returning this Flux from spring-web-flux controller we mark it as nack(false), that will send the message to the dead-letter-exhange, we can then have some redirect tricky that will move messages around, and a consumer can intercept them and based on some state updated by the clients through a http endpoint we can decided to let the message go back to the original queue or just discard them from rabbit (because they were processed and marked as such by the client). 

I think then our best option would be to change from http streaming to a single response, that uses the `qos` to limit the number of the messages we want to return, that will work basically as a polling proxy, can achieve this with the consumeManualAck, or i better falling back to the non reactive `Channel` methods? Would be possible to expose the MonoChannel or event the Connection used by the current Receiver/Option to avoid having to create and manage a new one, or that can cause issues?

That probably doesn't like a great idea, but is the only way we have now to support such clients.

**Comment by acogoluegnes** [comment]
> I think keeping the reference you mentioned would work for some cases, but if that channel is closed we no longer have the way to ack the message, or if we run more than one replica we also cannot guarantee we have the channel.

If the channel is closed, the un-acked messages delivered through it will go back to the queue.

> I think then our best option would be to change from http streaming to a single response, that uses the `qos` to limit the number of the messages we want to return, that will work basically as a polling proxy, can achieve this with the consumeManualAck, or i better falling back to the non reactive `Channel` methods? Would be possible to expose the MonoChannel or event the Connection used by the current Receiver/Option to avoid having to create and manage a new one, or that can cause issues?

A message must be acknowledged with the channel it has been delivered on, so you need to keep a reference to the channel somehow. That's why I suggested a new `java.util.function.Consumer<Channel>` property in `ConsumeOptions` that would let you do anything you want with the channel.

**Comment by mxandeco** [comment]
> A message must be acknowledged with the channel it has been delivered on, so you need to keep a reference to the channel somehow. That's why I suggested a new `java.util.function.Consumer<Channel>` property in `ConsumeOptions` that would let you do anything you want with the channel.

Yes I think that will work for us in most of the scenarios, and sounds like could be useful for other things, would be great if we could have access to that channel in the way you describe.

**Comment by acogoluegnes** [comment]
OK, I created #141 to follow up, closing this one. Feel free to submit a PR.

**Comment by acogoluegnes** [comment]
@mxandeco The channel callback has been implemented, you can test 1.4.4 snaphots: https://repo.spring.io/libs-snapshot/io/projectreactor/rabbitmq/reactor-rabbitmq/1.4.4.BUILD-SNAPSHOT/

There should be a release next week.

**Comment by mxandeco** [comment]
> @mxandeco The channel callback has been implemented, you can test 1.4.4 snaphots: https://repo.spring.io/libs-snapshot/io/projectreactor/rabbitmq/reactor-rabbitmq/1.4.4.BUILD-SNAPSHOT/
> 
> There should be a release next week.

Thanks @acogoluegnes for this feature, I have start to make the change, but I never had time to understand and add tests for them.

I will give it a try. Thanks very much.
