### ISSUE TITLE
Ensure automatic recovery is enforced correctly

### ISSUE THREAD

**Issue by bduisenov** [reactor/reactor-rabbitmq#14]
Hi, 
Could you show an example how to either reconnect using the same sender or to renew a sender?

**Comment by acogoluegnes** [comment]
Automatic connection recovery is managed by the underlying RabbitMQ Java client. Nevertheless this must be handled explicitly on sending and there's no support for this right now in Reactor RabbitMQ IIRC.

**Comment by acogoluegnes** [comment]
@bduisenov Thanks for pointing this out. Before this is tested and implemented in the library, you can use Reactor's usual operators if something goes wrong in the flow.

**Comment by acogoluegnes** [comment]
@bduisenov There should be now good support to handle connection failures, see https://projectreactor.io/docs/rabbitmq/snapshot/reference/#_error_handling_during_publishing and https://projectreactor.io/docs/rabbitmq/snapshot/reference/#_connection_failure. Feedback is welcome before we cut a second milestone. Thanks!
