### ISSUE TITLE
Support direct reply-to

### ISSUE THREAD

**Issue by travikk** [reactor/reactor-rabbitmq#15]
Hi there.

So I stumbled upon an interesting issue with this library. Currently, it seems as though reactor-rabbitmq does not support fast track direct reply-to mechanism, which is offered by RabbitMQ (https://www.rabbitmq.com/direct-reply-to.html).

After some research and debugging I found out that the issue is because currently Sender/Receiver use different channels for setting up the connection. The requirement to use direct reply-to is that, both the publish and consume happen via the same channel, so that the response can be routed to a specific consumer.

Moreover, it turns out that declaring a queue without a name (i.e. a replyTo queue) will get you nowhere either, as it is declared as an exclusive queue which only the sender will be able to use (since only the Sender has capability to declare queues). That's kind of useless, since in most cases you'll want to setup a consumer as well, expecting a reply.

I think giving developers choice over how consumer are used would be a good place to start. Building an abstraction layer over that, to support explicitly replyTo/direct replyTo would be even better, but naturally more time consuming.

The workaround for this issue is to create a custom queue per client and listen on that queue. It adds a small complexity in that you'll need to introduce some sort of correlationId for each request, as your client will receive potentially multiple responses for making multiple requests, which isn't too bad.

Please let me know what you think,
Konrad

**Comment by acogoluegnes** [comment]
We're planning to use a `Supplier<Connection>` (not yet sure about the exact API) to be able to use the same connection between `Sender`s and `Receiver` (see #12 and #13).

Could you please be more specific about your use case, e.g. provide some code of what you're doing now and another of what you'd like Reactor RabbitMQ to offer? The API isn't stable yet, so it's still possible to add support for request-reply (everything could fit in `Sender`).

**Comment by travikk** [comment]
Hmm, if you enable Supplier<Connection> to be passed in, that should fit the case I think.

Example of the code would be something along those lines:

`
receiver.consumeNoAck("amq.rabbitmq.reply-to").subscribe();

String payload = "test message";
OutboundMessage message = new OutboundMessage(
"my.exchange", 
"my.routing.key", 
new AMQP.BasicProperties.Builder().replyTo("amq.rabbitmq.reply-to").build(), 
payload.getBytes()
);

sender.send(Mono.just(message))
`

Sender will throw an exception saying that there's "fast reply consumer does not exist" due to the fact of both sender and receiver using different channels.

**Comment by travikk** [comment]
@acogoluegnes nice one, thanks for the work! One thing I noticed is that you're effectively overriding correlationId.
That might be a problem, when someone needs to set a custom corelationId

**Comment by acogoluegnes** [comment]
@travikk OK, I added an `Supplier<String>` arguments when creating the `RpcClient`, it should do the trick.
