### ISSUE TITLE
Switch to Github Actions for CI

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor-rabbitmq#150]
See reactor/reactor#690 for context.

This includes both PR checks and push checks on maintenance branches.
We'll also need to remove `travis.yml` file

**Comment by acogoluegnes** [comment]
Closed with the commits below.

`master`:
425f4d6676379c58e063bed2513ccdee2dcf809c
fee26466112f66805d198677ea8cd2b5ea5820e2
5e3b5c2974b31e9dfa08990377ac1f61a4c1616a
7d71b7883c7183db859d53361578e20b2725a1d8
61dded8ffc86e99e581b4c1675ba7b0c68312f27
879fbf4bd64c877541bb584ed4cb31031ab3d085
461001164530b6dd239e905806dbcb4c1b48612a
ebb71c1f81cf87728eb6a714bdd091285ae6a63d
72762637133bb81a0959a0ab053933e419181f1b
39a39a06dcd9da9d2a0a0783dabec2349617dd68

`1.4.x`:
afb1145e528157086c1745343ec8be50caa1a12c
25d4a832ba0890ba6a62f08d8af4cd720ca3d51b
2ef32a148c9f1b0156efabb80937ee8050624345
f4ca842f4e6351f40114b7cd5a9502fa5e548937
dd1c2a2df63076c975310321180fe668859c331f
