### ISSUE TITLE
Provide a way to specify Consumer Arguments in Receiver.consume* methods

### ISSUE THREAD

**Issue by maciejharczuk** [reactor/reactor-rabbitmq#165]
It looks like it's not possible to specify Consumer arguments when using any of the Receiver's `consume*` methods. I'm not sure if there was any use for them in the past, but with RabbitMQ 3.9 streams, if consuming them with AMQP client, the `x-stream-offset` argument is used to specify the offset at which consumption will start. 

Since we already have the ability to pass `ConsumeOptions` to `Receiver.consume*` methods, I suggest we add an empty-by-default (or null) map of args to that class, so that later we can pass it to `channel.basicConsume`.

**Comment by latuszek** [comment]
@acogoluegnes, is there a plan to release this any time soon?

**Comment by acogoluegnes** [comment]
It's in 1.5.4 and 1.4.8.RELEASE.

**Comment by latuszek** [comment]
OK, I must have missed it because of the not updated [releases](https://github.com/reactor/reactor-rabbitmq/releases) page. Thanks.
