### ISSUE TITLE
Pulsar and RabbitMQ integration

### ISSUE THREAD

**Issue by lynch19** [reactor/reactor-rabbitmq#171]
There is currently support for Apache Kafka. The usage of Project Reactor is currently pretty limited since this is the only integration of it (excluding DBs). A native integration with Apache Pulsar and RabbitMQ would be great for the ecosystem of Project Reactor. These integrations are very wanted features in my opinion.

**Comment by acogoluegnes** [comment]
There is a Reactor RabbitMQ integration. I can't comment on a Reactor Pulsar integration, I'd recommend to ask the question on the usual Pulsar development channels.

**Comment by acogoluegnes** [comment]
This repository is about the integration between RabbitMQ and Reactor, not Apache Pulsar, which is another product.
