### ISSUE TITLE
Receiver does not recover or catch the exception when there is a rabbitmq delivery acknowledgement timeout

### ISSUE THREAD

**Issue by yohasakur** [reactor/reactor-rabbitmq#178]
Hi, the problem I have is that my receiver does not recover or catch the exception when there is a rabbitmq delivery acknowledgement timeout "Channel error on connection <####> : operation none caused a channel exception precondition_failed: consumer ack timed out on channel 1". 
The receiver thinks that the connection is still open but rabbitmq already closed the connection.

## Expected Behavior

 I think it should auto recover in this case (creating a new connection ) or at least have the ability to know that the connection was closed.
## Actual Behavior

when there is a rabbitmq delivery acknowledgement timeout "Channel error on connection <####> : operation none caused a channel exception precondition_failed: consumer ack timed out on channel 1". 
The receiver thinks that the connection is still open but rabbitmq already closed the connection.
## Steps to Reproduce

Create a receiver bean and when you receive a message don't ack the message for more than 31m (default timeout is 30m)
```java
@Test
void reproCase() {

}
```

## Possible Solution

I know I can change delivery acknowledgement timeout but if there was a case where this situation happens I want it to auto recover or at least have the ability to handle it.
## Your Environment

* Reactor version(s) used: I am using reactor rabbitmq v1.5.5
* Other relevant libraries versions (eg. `netty`, ...):
* JVM version (`java -version`): 15
* OS and version (eg `uname -a`): debian  bullseye

**Comment by acogoluegnes** [comment]
Can you try changing the [connection recovery predicate](https://projectreactor.io/docs/rabbitmq/release/reference/#_connection_failure) to kick in recovery on the timeout error?

**Comment by yohasakur** [comment]
Do you mean this:
Receiver receiver = RabbitFlux.createReceiver();
BiConsumer<Receiver.AcknowledgmentContext, Exception> exceptionHandler =
    new ExceptionHandlers.RetryAcknowledgmentExceptionHandler(                  
        Duration.ofSeconds(20), Duration.ofMillis(500),
        ExceptionHandlers.CONNECTION_RECOVERY_PREDICATE
);
receiver.consumeManualAck("queue",
            new ConsumeOptions().exceptionHandler(exceptionHandler))
        .subscribe(msg -> {
            // ...                                                              
            msg.ack();                                                          
        });
because I am already doing it and it doesn't fix the issue.

**Comment by yohasakur** [comment]
Do you mean this:
Receiver receiver = RabbitFlux.createReceiver();
BiConsumer<Receiver.AcknowledgmentContext, Exception> exceptionHandler =
    new ExceptionHandlers.RetryAcknowledgmentExceptionHandler(                  
        Duration.ofSeconds(20), Duration.ofMillis(500),
        ExceptionHandlers.CONNECTION_RECOVERY_PREDICATE
);
receiver.consumeManualAck("queue",
            new ConsumeOptions().exceptionHandler(exceptionHandler))
        .subscribe(msg -> {
            // ...                                                              
            msg.ack();                                                          
        });
because I am already doing it and it doesn't fix the issue.

**Comment by acogoluegnes** [comment]
I'm suggesting to change `ExceptionHandlers.CONNECTION_RECOVERY_PREDICATE` to recover also on the consumer timeout exception.
