### ISSUE TITLE
 Cannot construct instance of `com.rabbitmq.client.Delivery` (no Creators, like default construct, exist)

### ISSUE THREAD

**Issue by duyleduc** [reactor/reactor-rabbitmq#18]
Could you add an empty constructor in Delivery please? 
I need consume a sse webservice in Java which returns a Flux<Delivery> but I could convert from json value to Delivery object.

**Comment by acogoluegnes** [comment]
`Delivery` is part of the [AMQP Java client](https://github.com/rabbitmq/rabbitmq-java-client), not Reactor RabbitMQ. Would it be enough to subclass it in your application and provide an empty constructor that calls the parent class constructor?

**Comment by duyleduc** [comment]
Thanks you, I have another solution :) It's for webclient to make a request to a streaming web service.
