### ISSUE TITLE
RpcClient Flux replaced with Mono publisher

### ISSUE THREAD

**Issue by pmackowski** [reactor/reactor-rabbitmq#32]
According to the API RpcClient class expects Publisher. 
```
public Mono<Delivery> rpc(Publisher<RpcRequest> request) {
        return channelMono.flatMap(channel -> new RpcOperator(request, channel));
}
```
When Flux is passed as an argument, only first item is consumed. Here is the reason why

```
private class RpcOperator extends MonoOperator<RpcRequest, Delivery> {

        private final Channel channel;

        protected RpcOperator(Publisher<RpcRequest> source, Channel channel) {
            super(Mono.from(source));
            this.channel = channel;
        }

        @Override
        public void subscribe(CoreSubscriber<? super Delivery> actual) {
            source.subscribe(new RpcSubscriber(channel, actual));
        }
}
```
Could you explain the rationale behind such decision and why haven't you chosen FluxOperator or
Mono as an argument in rpc method?

**Comment by acogoluegnes** [comment]
As a convention and to remain as open as possible to other reactive frameworks, we use Reactive Streams types for arguments. This is the same e.g. `Sender#send(Publisher<OutboundMessage>)`. I understand this can be confusing in `RpcClient#rpc`, but we don't have other choice as Reactive Streams use the same type whatever the number of emitted is.

**Comment by pmackowski** [comment]
Thank you for clarification. It is clear for me now.
