### ISSUE TITLE
Rename ReactorRabbitMQ -> RabbitFlux ?

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-rabbitmq#4]
As title says

**Comment by wxlund** [comment]
Is there any reason not to put the spring label on as well?

Spring-webflux
Spring-rabbitflux

I hope it looks side by side like we’re doing with mongo driver, web, etc.

**Comment by acogoluegnes** [comment]
@wxlund Reactor RabbitMQ is based on Reactor Core and RabbitMQ Java client, it does not depend at all on Spring.

**Comment by wxlund** [comment]
That makes sense. Probably not the right place to ask but is there a planned path from spring-amqp to spring-amqp-reactor?

**Comment by acogoluegnes** [comment]
@wxlund Not that I'm aware of. Right now, the closest would be to use Spring Integration 5.0 with the reactive support. /cc @garyrussell @artembilan.

**Comment by artembilan** [comment]
@wxlund,

Contribution is welcome, but I'm not sure that it is going to be a separate module. Maybe simple pair of Spring-wrappers around `Sender` and `Receiver` in the existing `spring-rabbit` is enough...

**Comment by artembilan** [comment]
And right: Spring Integration `5.0` can already be used with this Reactive components. I presented last SpringOne possible approach with `reactor-kafka`: 

https://github.com/artembilan/spring-integration-s1p2017/blob/master/src/test/java/org/springoneplatform2017/integration/kafka/SpringIntegrationS1p2017KafkaTests.java#L82-L95

**Comment by acogoluegnes** [comment]
@smaldini No objections to that. Is it a common convention between Reactor-based extension?

**Comment by acogoluegnes** [comment]
Per conversation with @simonbasle, we'll stick to the current name.

**Comment by acogoluegnes** [comment]
As per discussion with @simonbasle and @smaldini, addressing this one for consistency with other static helpers in the Reactor ecosystem.
