### ISSUE TITLE
Please put the RC2 artifact on maven central

### ISSUE THREAD

**Issue by mbaechler** [reactor/reactor-rabbitmq#40]
Hi, thank you for your library that is really helpful.
I started to use it in Apache James project but as long as the artifact is not in maven central I can't merge my code.
Would you mind uploading it ?

**Comment by acogoluegnes** [comment]
Thanks for using Reactor RabbitMQ, I'm glad you find it useful.

Unfortunately we don't publish milestones and release candidates on Maven Central. They are available on [Spring Milestones](https://repo.spring.io/milestone), as documented in the readme. The GA is just around the corner (next week) and it will be uploaded on Maven Central.

**Comment by mbaechler** [comment]
Thank your for the information, I'll wait for next week then.
