### ISSUE TITLE
RabbitMQ sender.declareQueue() non exclusive queue but create exclusive queue

### ISSUE THREAD

**Issue by trantienduchn** [reactor/reactor-rabbitmq#44]
Hello guys, I am using reactor-rabbitmq, it's awesome! But I got an unexpected result when creating a queue:
```java
sender.declareQueue(QueueSpecification.queue("my-work-queue")
            .durable(true)
            .exclusive(false)
            .autoDelete(false)
            .arguments(NO_ARGUMENTS))
            .block();
```
above code statement works. But When using rabbitmq management api to verify the result. I got the result of my work queue is an exclusive queue, and auto delete = true although I set them to false at queue declaration.

here is a part of json result getting from rabbitmq management api:
```
...
        "node": "rabbit@my-rabbit-9edfa11a-4fab-47b3-a9d1-40ef9504568b",
        "arguments": {},
        "exclusive": true,
        "auto_delete": true,
        "durable": false,
        "vhost": "/",
        "name": "amq.gen-GiAkGBT65IsO-va4DEYtGw",
...
```

I am using 
```
            <dependency>
                <groupId>io.projectreactor.rabbitmq</groupId>
                <artifactId>reactor-rabbitmq</artifactId>
                <version>1.0.0.RELEASE</version>
            </dependency>
```
and rabbitmq docker image from `rabbitmq:3.7.7-management`

**Comment by trantienduchn** [comment]
Hi @acogoluegnes, very sorry for my poor issue prepare. Yes you're right, it makes me verify my steps to get this issue again. This time I wrote a simple test in [my repository](https://github.com/trantienduchn/test-docker/blob/master/src/test/java/duc/home/test/docker/rabbitmq/ExclusiveQueueCreationTest.java) to get more proof.

When declaring queue without name `durable`, `exclusive`, `auto_delete` have reverse values, but with name, it's alright.
. BTW, Sorry for that poor report. Could you check it?

**Comment by pmackowski** [comment]
@acogoluegnes [according to this](https://github.com/reactor/reactor-rabbitmq/blob/master/src/main/java/reactor/rabbitmq/Sender.java#L187-L194) if name is null then queue is always exclusive and autodelete is true

**Comment by acogoluegnes** [comment]
@trantienduchn This behavior is expected. Reactor RabbitMQ is opinionated here, if you don't specify any name for the queue, it creates a non-durable, exclusive, auto-delete queue (see the code that @pmackowski pointed out). This makes it easy to create such queues.

If you want the server to generate the queue name, just specify an empty (`""`) name in the `QueueSpecification`. Hope this makes more sense.

**Comment by trantienduchn** [comment]
Glad to have that suggestion!!
Thank you both of you for your supports. I think I can close this issue now!

**Comment by trantienduchn** [comment]
Hello guys, when declaring a `QueueSpecification`, I feel not comfortable when the APIs still allow me to configure null name with various value of `durable, exclusive, auto-delete` properties. And there are no warning generated to the client that my configuration doesn't work like I configured it. So I propose I change for `QueueSpecification`.
When declare new `QueueSpecification` with null name, runtime will throw an exception if you configured `durable, exclusive, auto-delete` with non-expected values. Therefore, RabbitMQ Reactor tell me my configuration is invalid. With me it's still better than doing thing implicitly without notifying to clients. 

Here is my pull request https://github.com/reactor/reactor-rabbitmq/pull/51
Please check it! Thank you guys!
