### ISSUE TITLE
Receiver does not have "declareQueue" method

### ISSUE THREAD

**Issue by mszarlinski** [reactor/reactor-rabbitmq#5]
As we can see in [this](https://github.com/reactor/reactor-rabbitmq/blob/master/reactor-rabbitmq-samples/src/main/java/reactor/rabbitmq/samples/SampleReceiver.java#L51) example, to connect a `Receiver` we must use `declareQueue` method which is available only in `Sender` API. It looks a bit strange - why one should create a `Sender` instance just to register a `Receiver`?

I wonder why it is not available on the `Receiver` side - but I'm sure I'm missing something important.

**Comment by acogoluegnes** [comment]
The queue just needs to exist before trying to consume from it, that's why there's a `Sender` call before `Receiver#consumeAutoAck`. Does that make sense?

**Comment by mszarlinski** [comment]
Of course, thank you for clarification.

**Comment by pmalipio** [comment]
Shouldn't this work without declaring the queue?

Flux<Delivery> deliveryFlux = receiver.consumeNoAck(queueName);
deliveryFlux.subscribe(m -> System.out.println(SerializationUtils.deserialize(m.getBody())));

**Comment by acogoluegnes** [comment]
@pmalipio It'll work as long as the queue already exists. Creating the queue in this sample makes it standalone, there's no need to create the queue manually.

**Comment by pmalipio** [comment]
Ok, thanks.
