### ISSUE TITLE
New isolated thread created ?

### ISSUE THREAD

**Issue by smaldini** [reactor/reactor-rabbitmq#64]
Maybe replace the following https://github.com/reactor/reactor-rabbitmq/blob/34629edb1cbd532587da976c4d88062b905933c1/src/main/java/reactor/rabbitmq/Sender.java#L464 with a global reactor thread like Schedulers.parallel() or single() given the underlying logic is not blocking.

**Comment by pmackowski** [comment]
@smaldini You are refering to the part of the code that no longer exist (v1.0.0). It has been replaced in v1.1.0 with [cached thread pool](https://github.com/reactor/reactor-rabbitmq/commit/3a083cd02e4cad251bcc47fb5157a97f2334cc45). It is a blocking logic unless channel pooling is used. 
Any your comments on that are highly appreciated:)

**Comment by acogoluegnes** [comment]
This issue is indeed fixed as of 1.1.0.
