### ISSUE TITLE
Publisher confirms - maxInFlight

### ISSUE THREAD

**Issue by pmackowski** [reactor/reactor-rabbitmq#66]
[reactor-kafka](https://github.com/reactor/reactor-kafka) supports backpressure through so called maxInFlight option:
> The number of in-flight sends can be controlled using the maxInFlight option. Requests for more elements from upstream are limited by the configured maxInFlight to ensure that the total number of requests at any time for which responses are pending are limited ..... maxInFlight enables control of memory and thread usage when KafkaSender is used in a reactive pipeline. This option can be configured on SenderOptions before the KafkaSender is created. Default value is 256. For small messages, a higher value will improve throughput.

@acogoluegnes Here is a draft how it could be implemented [max-in-flight-draft](https://github.com/reactor/reactor-rabbitmq/compare/master...pmackowski:63-sender-confirm-backpressure) I think that this functionallity might be helpful even if it does not solve [#63](https://github.com/reactor/reactor-rabbitmq/issues/63) issue. What do you think? Please also look into test `RabbitFluxTests#publishConfirmsErrorWhilePublishing()` I had to change it to pass after adding this functionality.

Btw. I wonder what is the advantage of new implementation `publish-confirms-as-in-the-white-rabbit` over existing one?

**Comment by acogoluegnes** [comment]
> Btw. I wonder what is the advantage of new implementation publish-confirms-as-in-the-white-rabbit over existing one?

It is just a way to compare both (Reactor RabbitMQ's and the White Rabbit's) publish confirm handling strategy. I may introduce a pluggagle strategy in 1.2.0 though.

**Comment by acogoluegnes** [comment]
Fixed by #67.
