### ISSUE TITLE
Support client-generated consumer tags

### ISSUE THREAD

**Issue by philsttr** [reactor/reactor-rabbitmq#96]
I'd like the ability to provide a client-generated consumer tag via `ConsumeOptions`.

Currently, only server-generated consumer tags are supported.  e.g. [here](https://github.com/reactor/reactor-rabbitmq/blob/1a76781cf958c1d91b47ce946f62ab4069c48637/src/main/java/reactor/rabbitmq/Receiver.java#L179)

**Comment by acogoluegnes** [comment]
Fixed by #97.
